{"author": "Albert Einstein", "author_link": "/author/Albert-Einstein", "text": "\u201cThe world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.\u201d", "tags": ["change", "deep-thoughts", "thinking", "world"], "text_hash": "8fad692e2aa0977fe73529e9a3fa3472"}
{"author": "J.K. Rowling", "author_link": "/author/J-K-Rowling", "text": "\u201cIt is our choices, Harry, that show what we truly are, far more than our abilities.\u201d", "tags": ["abilities", "choices"], "text_hash": "09ae098cde4158dcd31dd950c34eeb57"}
{"author": "Albert Einstein", "author_link": "/author/Albert-Einstein", "text": "\u201cThere are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.\u201d", "tags": ["inspirational", "life", "live", "miracle", "miracles"], "text_hash": "63b4ad22351de9b55c64a0a3f1f075f4"}
{"author": "Jane Austen", "author_link": "/author/Jane-Austen", "text": "\u201cThe person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.\u201d", "tags": ["aliteracy", "books", "classic", "humor"], "text_hash": "9244aec5e91041971c11159d598250a1"}
{"author": "Marilyn Monroe", "author_link": "/author/Marilyn-Monroe", "text": "\u201cImperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.\u201d", "tags": ["be-yourself", "inspirational"], "text_hash": "9b9abb772f6165033b88920b3a876721"}
{"author": "Albert Einstein", "author_link": "/author/Albert-Einstein", "text": "\u201cTry not to become a man of success. Rather become a man of value.\u201d", "tags": ["adulthood", "success", "value"], "text_hash": "48d0fd0a272c2d98856b7508de58b52c"}
{"author": "Thomas A. Edison", "author_link": "/author/Thomas-A-Edison", "text": "\u201cI have not failed. I've just found 10,000 ways that won't work.\u201d", "tags": ["edison", "failure", "inspirational", "paraphrased"], "text_hash": "edacf0faf15511d40390212e86a63b9a"}
{"author": "Eleanor Roosevelt", "author_link": "/author/Eleanor-Roosevelt", "text": "\u201cA woman is like a tea bag; you never know how strong it is until it's in hot water.\u201d", "tags": ["misattributed-eleanor-roosevelt"], "text_hash": "30c45f81c5b290241a37f30af0b38a2e"}
{"author": "Steve Martin", "author_link": "/author/Steve-Martin", "text": "\u201cA day without sunshine is like, you know, night.\u201d", "tags": ["humor", "obvious", "simile"], "text_hash": "d69ac0b362319b9489e59a7e1f2efa7c"}
